-- ===========================================================================
--  伙伴台词配置文件 / Companion dialogue configuration
--  ---------------------------------------------------------------------
--  这个文件是伙伴所有台词的唯一来源，随便改，不会影响其他逻辑。
--
--  1. lines 里的每一组都是"随机台词"，伙伴会从中随机挑一条说出来。
--     每一条写成 {"中文", "English"}，两种语言都要留着（按模组语言设置显示）。
--     一组里至少保留 1 条；想让随机效果好一些，建议每组 4 条以上。
--
--  2. replies 里的每一条都是"固定回复"，只有一条 {"中文", "English"}。
--
--  3. 文本里可以写 {1}，伙伴说话时会替换成对应的名字或数字。
--     如果这一条没有写 {1}，但是程序带了名字过来，
--     伙伴会自动说成 "名字，台词内容"。
--
--  4. 不要删除任何一组的名字（等号左边的 key），只改引号里的文字最安全。
--     新增台词就在花括号里多加一行即可。
--
--  5. 普通台词以头顶气泡 + 附近玩家聊天框播出；到来、告别、鬼魂求助为世界公屏公告。
-- ===========================================================================

local M = {}

M.lines = {
    pet_feed = {
        {"饿了吧，小家伙，来吃一口。", "Hungry, little one? Here, have a bite."},
        {"这点小零食留给你，慢慢吃。", "This little snack is for you. Take your time."},
        {"别围着我转啦，知道你饿了。", "No need to circle me. I know you're hungry."},
        {"吃饱了再陪我走一会儿。", "Have a bite, then let's walk some more."},
    },
    pet_travel = {
        {"材料带齐了，去巢穴接个小伙伴。", "Supplies ready. I'm off to meet a little companion."},
        {"不知道它见到我会不会开心呢。", "I wonder if it'll be happy to meet me."},
        {"等我回来，咱们就多一位朋友了。", "We'll have another friend when I get back."},
    },
    pet_adopt = {
        {"来吧，以后我们一起走。", "Come along. We'll travel together from now on."},
        {"给你准备了好吃的，跟我回家吧。", "I've brought you a treat. Come home with me."},
        {"小家伙，以后我照顾你。", "I'll take care of you, little one."},
    },
    explore = {
        {"这边还没走过，我去看看。", "I haven't been this way. Let's take a look."},
        {"路我记着呢，叫我一声就回来。", "I'm keeping track of the route. Call me when you need me."},
        {"先照顾好自己，再接着往前走。", "I'll take care of myself, then keep exploring."},
        {"绕过这片树林，看看另一边有什么。", "Let's see what's beyond these woods."},
    },
    explore_mount = {
        {"有牛儿同行，今天能走远一些了。", "With a beefalo along, we can explore a little farther."},
        {"借你的脚力，去看看没走过的地方。", "Let's ride out somewhere we haven't been."},
        {"事情忙完了，骑上牛继续探路。", "All taken care of. Back in the saddle to explore."},
    },
    explore_dismount = {
        {"找块好落脚的地方，我先下来一下。", "Let's find some clear ground. I need to get down for a moment."},
        {"这段先用脚走，探路的事还记着呢。", "I'll walk this stretch. I'm still exploring."},
        {"先下牛处理点事情，忙完再继续走。", "I'll get down to take care of something, then carry on."},
    },
    fish_prepare = {
        {"先把钓竿备好，鱼儿可不等人。", "First, a fishing rod. The fish won't wait forever."},
        {"找找钓竿，没有就做一根。", "I'll find a rod, or make one."},
        {"材料凑齐了，再去池塘边坐坐。", "Once the supplies are ready, I'll head to a pond."},
    },
    fish_search = {
        {"附近没有合适的池塘，再往前找找。", "No suitable pond here. I'll keep looking."},
        {"这边的鱼暂时钓不了了，换个地方。", "I can't fish here for now. Let's try elsewhere."},
        {"钓竿带好了，就差一处好水塘。", "Rod ready. Now I just need a good pond."},
    },
    fish_replace = {
        {"钓竿用坏了，看看身上的材料还能不能再做一根。", "The rod wore out. Let's see if I can make another with what I'm carrying."},
        {"先补一根钓竿，再回来等鱼上钩。", "I'll replace the rod, then get back to fishing."},
        {"钓竿也得换班，材料够就继续。", "Time for a fresh rod, if I have the supplies."},
    },
    fish_cast = {
        {"就在这里下竿吧。", "This looks like a good place to cast."},
        {"安静等一等，看看今天的收获。", "A little patience. Let's see what bites."},
        {"鱼儿，上钩吧。", "Come on, fish. Take the bait."},
    },
    fish_caught = {
        {"又钓到一条，收好了。", "Another catch, safely packed."},
        {"这条留着做顿好饭。", "This one will make a nice meal."},
        {"收获不错，再来一竿。", "A good catch. Let's cast again."},
    },
    fish_full = {
        {"身上装不下了，鱼先放岸边。", "My pockets are full. I'll leave the fish on the bank."},
        {"这条先放这里，回头记得来拿。", "I'll leave this one here to pick up later."},
        {"鱼比口袋多啦，先摆在脚边。", "More fish than pocket space. I'll leave it here."},
    },
    butterfly_hunt = {
        {"得再靠近一点，这小家伙飞得可快。", "A little closer. This one flies fast."},
        {"先盯住这一只，别让它飞远了。", "I'll keep my eye on this one."},
        {"等我靠近了再出手。", "I'll get close before I swing."},
        {"这回得跟紧些，不能挥空了。", "Stay close this time. No swinging at thin air."},
    },
    butterfly_loot = {
        {"拿到了，先把吃的收好。", "Got it. Let's pick up the food."},
        {"这一点也能救急，不能落下。", "Even a little can help in a pinch."},
        {"先捡起来，再看要不要继续。", "I'll pick this up before deciding what's next."},
    },
    ghost_help = {
        {"我是{1}，不小心变成鬼魂了，有人能来救救我吗？", "It's {1}. I've become a ghost. Could someone help revive me?"},
        {"{1}在这里求救！谁方便带颗救赎之心来？我的东西还掉在原地呢。", "{1} needs help! Could someone bring a Telltale Heart? My belongings are still where I fell."},
        {"我是{1}，现在只能飘着了。有空的朋友帮我复活一下吧。", "It's {1}, floating around as a ghost. Could a friend spare a moment to revive me?"},
        {"{1}还在等救援，谁能帮我重新站起来？等活过来再好好谢谢你。", "{1} is waiting for rescue. Can someone bring me back? I'll thank you properly once I'm alive."},
        {"我是{1}，这次真的需要帮忙了！有人愿意过来救我吗？", "It's {1}. I could really use some help this time! Could someone come revive me?"},
    },
    ghost_help_depart = {
        {"我是{1}，大家先忙吧，我自己飘去大门复活，之后回来捡东西。", "It's {1}. Carry on, everyone. I'll float to the portal to revive, then return for my belongings."},
        {"{1}准备去大门复活了，不用特地赶来啦，我还得回来收拾遗物呢。", "{1} is heading to the portal to revive. No need to rush over; I'll come back for my things."},
        {"我是{1}，看来大家都挺忙，我先去大门找回身体，再回来拿自己的东西。", "It's {1}. Everyone seems busy. I'll revive at the portal and come back for my things."},
    },
    skin_changed = {
        {"换好了！你觉得这身怎么样？", "All changed! What do you think?"},
        {"你挑的这套还挺合适，谢谢啦。", "This outfit suits me. Thanks for picking it out."},
        {"新造型，新心情，今天走路都精神些了。", "A new look lifts the spirits. I have a spring in my step!"},
        {"让我转一圈，你帮我看看有没有哪里不整齐。", "Let me turn around. Does everything look tidy?"},
        {"穿得这么好看，等会儿干活可得小心点。", "Looking this nice, I'd better be careful with the chores."},
        {"眼光不错嘛，下回还找你帮我挑。", "You have good taste. You can help me choose next time too."},
        {"这下见到熟人，他们还能一眼认出我吗？", "Will our friends recognize me in this?"},
        {"收拾得焕然一新，咱们接着出发吧。", "All freshened up. Let's get going."},
        {"怎么样，有没有比刚才更像个可靠的伙伴？", "Do I look like an even more dependable companion now?"},
        {"有你帮忙挑衣服，倒省了我纠结半天。", "You've saved me ages of deciding what to wear."},
    },
    gather_hurt = {
        {"采这个会受伤，先换个地方，过一会儿再来。", "That hurt to gather. I'll try somewhere else for a while."},
        {"这份材料有点扎手，先让它待着吧。", "That resource bites back. I'll leave it alone for now."},
        {"刚才吃了点苦头，这个先记下来，暂时不碰。", "That cost me some health. I'll remember to avoid it for now."},
    },
    wormhole_follow = {
        {"等我一下，我也从这里过去。", "Wait for me. I'll follow you through."},
        {"你先过去，我马上就到。", "Go ahead. I'll be right behind you."},
        {"这条近路有点黏，不过总比绕远好。", "This shortcut is sticky, but it beats the long way."},
    },
    rift_follow = {
        {"等等我，这条裂隙我也能走吧？", "Wait for me. I can use this rift too, right?"},
        {"趁它还没合上，我这就跟过来。", "I'll follow before it closes."},
        {"你先过去，我马上从这边跳进来。", "Go ahead. I'll jump through right behind you."},
        {"这回的近路看着还挺神奇。", "Now that's an unusual shortcut."},
    },
    sit_rest = {
        {"这儿有把椅子，我坐一会儿，出发时叫我。", "There's a chair here. I'll rest a moment; tell me when we're going."},
        {"附近挺安静，让腿也歇一歇。", "It's quiet here. My legs could use a rest."},
        {"有现成的座位，就不站着发呆了。", "A perfectly good seat! No need to stand around."},
        {"坐着看看风景，你要走我就跟上。", "I'll enjoy the view. When you go, I'll follow."},
    },
    sit_together = {
        {"你也坐下了？那我就在旁边陪你一会儿。", "Taking a seat? I'll keep you company."},
        {"旁边还有空位，正好一起歇歇脚。", "There's a free seat nearby. Let's rest our feet."},
        {"今天走了不少路，坐下来聊两句吧。", "We've walked quite a way. Let's sit and chat."},
        {"好呀，一起坐会儿。等你休息好了再出发。", "Let's sit together. We can head out when you're rested."},
    },
    book_read = {
        {"让我翻到这一页，知识也需要耐心。", "Let me find the page. Knowledge takes patience."},
        {"听仔细了，这可不是普通的故事书。", "Listen closely. This is no ordinary storybook."},
        {"书里的办法，正好能派上用场。", "The answer in this book should come in handy."},
        {"这一段我记得，不过还是核对一下好。", "I remember this passage, but it pays to check."},
    },
    book_shelf_read = {
        {"书就在架子里，我打开书架直接读。", "The book is on the shelf. I'll open it and read here."},
        {"找到了，让它留在书架里就好。", "Found it. It can stay right on the shelf."},
        {"书不用搬来搬去，在这里读也一样。", "No need to carry it around. I can read it here."},
        {"读完就关好书架，知识也要好好保管。", "I'll close the shelf when I'm done. Knowledge deserves good care."},
    },
    book_ground_pickup = {
        {"书在地上，先捡起来再读。", "The book is on the ground. I'll pick it up before reading."},
        {"找到一本落在地上的书，别让它受潮了。", "I found a book on the ground. Let's keep it from getting damp."},
    },
    book_store = {
        {"这本书只剩最后一次了，放进书架养护一下。", "One reading left. This book needs some time on the shelf."},
        {"书页已经很旧了，先让它歇歇。", "These pages are worn. Let's give them a rest."},
        {"有书架就别急着把书用光，留着还能慢慢恢复。", "With a shelf nearby, we can let this book recover."},
        {"最后几页要爱惜，我先替你收好。", "These last pages need care. I'll put the book away."},
    },
    rockfruit = {
        {"石果交给我吧，硬的我来敲，软的我来摘。", "Leave the rock fruit to me. I'll mine the hard ones and pick the soft ones."},
        {"这果子长得像石头，脾气也确实像石头。", "These fruits look like rocks, and they certainly have the temperament of rocks."},
        {"先把附近的石果收好，别让它们在地上装无辜。", "I'll gather the nearby rock fruit before it pretends to be innocent on the ground."},
    },
    rockfruit_ask = {
        {"石果收好了，要我继续敲开，还是放进最近的箱子？", "The rock fruit is gathered. Should I mine it open, or put it in the nearest chest?"},
        {"硬邦邦的都在这儿了，你说敲不敲？三十秒内告诉我。", "The hard ones are ready. Should I crack them open? Tell me within thirty seconds."},
        {"要不要敲石果？你不说我就当它们只是普通收藏品。", "Should I crack the rock fruit? If you don't say, I'll call it a collection."},
    },
    rockfruit_mine_answer = {
        {"好，既然你点头了，我这就把石果敲开。", "All right, you said yes. I'll crack the rock fruit open."},
        {"收到，石头外壳准备接受命运吧。", "Message received. Rock shell, meet your destiny."},
    },
    rockfruit_store_answer = {
        {"好，不敲就不敲，我把它们收进箱子，留着以后再说。", "All right, no cracking. I'll store them for later."},
        {"行，今天先不和石果较劲，箱子会照顾好它们。", "Fine. I won't argue with the rock fruit today. The chest can look after it."},
    },
    bullkelp = {
        {"我去摘海带，顺便看看海边有没有把我吹成海带。", "I'll gather bull kelp and try not to become kelp myself."},
        {"海带都别躲，今天一个也别想漏网。", "Bull kelp, don't hide. None of you are escaping today."},
        {"摘完我就放进冰箱，给它们安排一个凉快的位置。", "I'll put the kelp in the fridge when I'm done and keep it cool."},
    },
    dry_meat = {
        {"我去给食材找个晾肉架，晒太阳总比在包里闷着好。", "I'll find the food a drying rack. Sunlight beats sweating in my bag."},
        {"晾肉架准备好了吗？我这就把能晾的都挂上去。", "Are the drying racks ready? I'll hang up everything that can be dried."},
        {"今天的菜单是风干，厨师本人暂时不参与风干。", "Today's menu is dried food. The chef is staying out of the drying process."},
    },
    dry_meat_collect = {
        {"晾好了？我来把这批风味收回来。", "Finished drying? I'll bring this batch of flavor back."},
        {"太阳干活很卖力，我负责把成果收进冰箱。", "The sun worked hard. I'll put the results in the fridge."},
        {"晾肉架今天交作业了，收货。", "The drying rack handed in its homework. I'll collect it."},
    },
    carry_statue = {
        {"这尊雕像有点沉，不过我搬得动。", "This statue is a little heavy, but I can carry it."},
        {"别催，我正和这块石头培养默契。", "Don't rush me. This stone and I are getting acquainted."},
        {"搬东西也是一种锻炼，今天的手臂有事做了。", "Carrying things is exercise. My arms have work today."},
    },
    carry_statue_mount = {
        {"骑牛搬雕像，今天的运输规格有点高。", "Carrying a statue on a beefalo is quite a transport upgrade."},
        {"牛儿，慢一点，咱们车上还有一位石头客人。", "Easy, beefalo. We have a stone passenger on board."},
        {"放心，雕像坐得比我还稳。", "Don't worry. The statue is sitting steadier than I am."},
    },
    -- ---------- 日常行为 ----------
    ride_mount = {
        {"离得太远了，骑牛过去会快些。", "You're too far away. Riding will be quicker."},
        {"牛儿，载我去找他吧。", "Come on, take me to them."},
        {"先借你的脚力赶路。", "I'll borrow your legs for the journey."},
    },
    ride_chase = {
        {"我骑牛追上去，很快就到。", "I'll ride after them. I'll catch up soon."},
        {"别走太远，我这就赶上。", "Don't go too far. I'll catch up."},
        {"有坐骑就不用担心赶不上了。", "With a mount, I won't have to worry about falling behind."},
    },
    ride_dismount = {
        {"到了这里，我走过去就好。", "This is close enough. I'll walk from here."},
        {"谢谢你载我一程。", "Thank you for the ride."},
        {"辛苦啦，接下来我们慢慢走。", "Good work. We can walk from here."},
    },
    follow = {
        {"好，我跟着你。", "Okay, I'm right behind you."},
        {"一起走吧，我就在身边。", "Let's go together. I'll be right here beside you."},
        {"你带路，我会跟上的。", "You lead the way, I'll keep up."},
        {"去哪里都好，我们一起。", "Anywhere's fine, as long as we go together."},
        {"嗯，别担心落下我。", "Mm. Don't worry about losing me."},
        {"我来啦，我们一起走。", "Coming! Let's go."},
    },
    idle = {
        {"这里很安静，歇一会儿吧。", "It's peaceful here. Let's rest a bit."},
        {"今天也慢慢来，不着急。", "Let's take today slowly. No rush."},
        {"有个能回来的地方，真好。", "It's good having somewhere to come back to."},
        {"我在附近走走。", "I'll wander around a bit."},
        {"每阵风都让我想起很多事情。", "Every gust of wind brings something back to me."},
        {"事情做完了，喘口气吧。", "That's done. Let's catch our breath."},
        {"我在检查今天的风有没有把我的发型吹乱。", "I'm checking whether today's wind ruined my hair."},
        {"暂时没大事，正好陪影子散散步。", "Nothing urgent. My shadow and I are taking a walk."},
        {"别看我发呆，我这是在认真恢复能量。", "Don't mind me. I'm seriously recharging."},
        {"风景不错，连发呆都有点舍不得结束。", "The view is nice. Even spacing out feels worthwhile."},
        {"我在附近待命，顺便想想晚饭吃什么。", "I'm on standby and thinking about dinner."},
        {"今天也辛苦啦，能歇一会儿就歇一会儿。", "We've worked hard today. Rest when we can."},
    },
    activity_idle = {
        {"没看见吗？我正在悠闲地待机，顺便观察风向。", "Can't you tell? I'm relaxing on standby and watching the wind."},
        {"暂时没急事，正替大家把安静的气氛维持住。", "Nothing urgent. I'm maintaining the peaceful atmosphere."},
        {"我在休息，休息也是生存计划的一部分。", "I'm resting. Resting is part of the survival plan."},
    },
    activity_chop = {
        {"没看见吗？我在砍树呀。", "Can't you tell? I'm chopping a tree."},
        {"我要准备点木头过冬用。", "I'm gathering wood for the coming winter."},
        {"不是你叫我砍树的吗？我这就快好了。", "Didn't you ask me to chop? I'm nearly done."},
    },
    activity_mine = {
        {"我在和石头谈判，目前它还不肯投降。", "I'm negotiating with this rock. It hasn't surrendered yet."},
        {"正在挖矿，看看今天能不能挖出点惊喜。", "I'm mining. Let's see if the ground has a surprise."},
        {"我在给基地准备石头和矿料。", "I'm collecting stone and ore for the base."},
    },
    activity_dig = {
        {"我在挖东西，地面马上就会变得更有规划。", "I'm digging. The ground will look more organized soon."},
        {"正在移植这些植物，给它们换个更好的住处。", "I'm transplanting these plants into a better home."},
        {"铲子在手，附近的草丛树苗都得排队。", "With a shovel in hand, the grass and saplings can take turns."},
    },
    activity_fish = {
        {"我在钓鱼，鱼竿比我还需要耐心。", "I'm fishing. The rod needs more patience than I do."},
        {"正在等鱼儿上钩，别把水面吓跑了。", "I'm waiting for a bite. Don't scare the pond."},
        {"我在给晚饭争取一点水产。", "I'm trying to bring some seafood home for dinner."},
    },
    activity_explore = {
        {"我在探图，看看世界还有什么没见过的角落。", "I'm exploring to see what corners of the world remain unknown."},
        {"正在开路，放心，我还记得回来的方向。", "I'm scouting ahead. Don't worry, I remember the way back."},
        {"我在出去逛逛，发现好东西就带回来。", "I'm out for a walk. I'll bring back anything useful."},
    },
    activity_fight = {
        {"我在打架呀，等我把这位客人请走。", "I'm fighting. Let me see this visitor out."},
        {"正在保护你，也顺便保护我自己。", "I'm protecting you, and myself while I'm at it."},
        {"我在处理麻烦，处理完就回来。", "I'm dealing with trouble. I'll be back when it's handled."},
    },
    activity_feed = {
        {"我在给小家伙喂饭，它的肚子比看起来诚实。", "I'm feeding the little one. Its stomach is honest."},
        {"正在照顾宠物，养宠物可不能只负责可爱。", "I'm caring for my pet. Cute is not the only responsibility."},
        {"我在给它准备一口吃的，马上就好。", "I'm getting it a bite to eat. Almost done."},
    },
    activity_tidy = {
        {"我在整理物资，箱子都快认识我了。", "I'm organizing supplies. The chests almost know me by name."},
        {"正在把没急用的东西安置好，免得它们到处旅行。", "I'm putting away spare things before they wander off."},
        {"我在收拾，基地总得有点秩序。", "I'm tidying up. A base needs some order."},
    },
    activity_cook = {
        {"我在做饭，今天的锅不会空着。", "I'm cooking. The pot won't stay empty today."},
        {"正在把食材变成更像样的晚餐。", "I'm turning ingredients into something more like dinner."},
        {"我在准备料理，等会儿记得趁热吃。", "I'm preparing a meal. Remember to eat it while it's warm."},
    },
    activity_eat = {
        {"我在吃饭，重要的生存会议正在召开。", "I'm eating. An important survival meeting is in session."},
        {"正在补充能量，空肚子可做不了大事。", "I'm refueling. An empty stomach can't accomplish much."},
        {"我在认真吃饭，别担心，没把你的份吃掉。", "I'm eating properly. Don't worry, I didn't take your portion."},
    },
    activity_build = {
        {"我在制作东西，材料马上就会变成有用的家当。", "I'm crafting. These materials will soon become something useful."},
        {"正在建造，基地要一点一点变得可靠。", "I'm building. A dependable base takes time."},
        {"我在忙着做东西，等成品出来你就知道了。", "I'm making something. You'll see when it's finished."},
    },
    activity_follow = {
        {"我在跟着你呀，难道我藏得太好了？", "I'm following you. Am I hiding too well?"},
        {"正在陪你走，顺便看看路边有没有好东西。", "I'm walking with you and watching for useful things."},
        {"我在你身边待命，你往哪儿走我就往哪儿走。", "I'm on standby beside you. I go where you go."},
    },
    activity_ride = {
        {"我在骑牛赶路，四条腿果然比两条腿忙。", "I'm riding. Four legs are certainly busier than two."},
        {"正在骑牛追上你，别跑得太快。", "I'm riding to catch up. Don't run too fast."},
        {"我在和牛一起赶路，今天的路程有坐骑负责。", "I'm traveling with my beefalo. The mount has today's distance covered."},
    },
    activity_sit = {
        {"我在坐着休息，椅子今天表现得很可靠。", "I'm resting. The chair is doing reliable work today."},
        {"正在坐着陪你，腿也需要一点尊重。", "I'm sitting with you. My legs deserve some respect too."},
        {"我在椅子上待命，叫我一声就出发。", "I'm on standby in this chair. Call me when it's time to go."},
    },
    work = {
        {"这件事交给我吧。", "Leave this one to me."},
        {"一点一点来，总能做好的。", "Bit by bit. We'll get there."},
        {"我会仔细些的。", "I'll be careful with it."},
        {"先把眼前的事情做好。", "Let's finish what's in front of us first."},
        {"忙一会儿，之后再休息。", "A little work now, rest after."},
        {"能帮上忙就好。", "I'm just glad I can help."},
    },
    chop = {
        {"这些木头应该够用一阵了。", "This wood should last us a while."},
        {"再备一点木头，夜里就安心些。", "A bit more wood and the night won't worry me."},
        {"小心，别站在树倒下的地方。", "Careful, don't stand where it's going to fall."},
        {"把木头带回去，还有不少用处。", "Let's take the wood back. We'll find plenty of uses for it."},
        {"一斧一斧地来。", "One swing at a time."},
        {"这些树长得真高。", "These trees have grown so tall."},
    },
    mine = {
        {"石头里也藏着有用的东西呢。", "There's good stuff hidden inside these rocks."},
        {"敲下来的碎石，别扎到脚。", "Mind your feet, these chips are sharp."},
        {"把这些矿石收好。", "Let's put these ores somewhere safe."},
        {"再敲几下试试。", "A few more swings should do it."},
        {"这些材料以后会用得上。", "We'll be needing these materials later."},
        {"坚硬的石头，也可以慢慢敲开。", "Even the hardest rock cracks if you keep at it."},
    },
    gather = {
        {"这个也带上吧。", "Let's take this one too."},
        {"慢慢收，不要漏掉了。", "Slow and steady, so we don't miss any."},
        {"有这些储备，就踏实多了。", "A stock like this puts my mind at ease."},
        {"路过能用的东西，就收好。", "If it's useful and it's on our way, I'll grab it."},
        {"这附近还有些东西可以收。", "There's still a bit more to pick up around here."},
        {"背包里又多了一点收获。", "A little more in the bag."},
    },
    plant = {
        {"在这里好好长大吧。", "Grow up strong here, little one."},
        {"以后这里会更绿一些。", "This place will be greener one day."},
        {"给你留好了位置。", "I saved a spot just for you."},
        {"慢慢长，我们会等的。", "Take your time growing. We'll wait."},
        {"把根安顿好，就不怕了。", "Settle your roots in and you'll be fine."},
        {"这一小片也有生气了。", "This little patch is waking up."},
    },
    fertilizer_search = {
        {"去草原看看，给基地找些肥料。", "I'll look for fertilizer on the savanna."},
        {"这一带找完了，再往前看看。", "I've checked this patch. Let's look a little farther."},
        {"草丛还等着肥料呢，我去找找。", "The grass tufts need fertilizer. I'll look for some."},
    },
    fertilizer_collect = {
        {"这份肥料带回去，草丛用得上。", "The grass tufts back home can use this."},
        {"收好这些，回基地再施肥。", "I'll take these home before fertilizing."},
        {"又找到一点肥料了。", "A little more fertilizer for the garden."},
    },
    fertilize = {
        {"给你补点养分，继续长吧。", "Some nutrients to help you grow again."},
        {"肥料用上了，等着草丛恢复。", "Fertilized. Now the grass can recover."},
        {"这一丛也照顾好了。", "That's another tuft taken care of."},
    },
    build = {
        {"这样就更像一个家了。", "Now it's starting to feel like home."},
        {"又做好了一件。", "That's one more done."},
        {"放在这里应该很合适。", "This should sit nicely right here."},
        {"准备周全些，之后就方便了。", "A bit of preparation now saves trouble later."},
        {"材料没有白费呢。", "None of those materials went to waste."},
        {"一点点把需要的东西补齐。", "Bit by bit, we'll have everything we need."},
    },
    store = {
        {"同样的东西放在一起，比较好找。", "Same things together, much easier to find."},
        {"把这些收好，以后用。", "I'll put these away for later."},
        {"整理一下，背包就轻松了。", "A quick tidy and the bag feels lighter."},
        {"需要的时候，就知道来哪里拿了。", "Now we'll know exactly where to look."},
        {"东西各有各的位置。", "Everything has a place of its own."},
        {"留一点备用，总是好的。", "It never hurts to keep a little spare."},
    },
    recipe_cook = {
        {"这些食材能凑一锅，做熟了更划算。", "These ingredients make a better meal together."},
        {"锅就在旁边，给自己做顿像样的饭。", "There's a pot here. Time for a proper meal."},
        {"先留着这几样，我有个好菜谱。", "I'll save these ingredients. I have a recipe in mind."},
        {"添好材料，接下来就交给火候了。", "Ingredients in. Now let the heat do its work."},
        {"冰箱里的材料正好够，今天不用啃生的了。", "There's enough in the fridge for a cooked meal today."},
    },
    recipe_clear = {
        {"锅里还有上次的材料，我先收好再开工。", "There are leftover ingredients in the pot. I'll put them away first."},
        {"这些还能用，找个合适的地方存起来。", "These are still useful. I'll find somewhere suitable to store them."},
        {"先腾出锅，接下来按你的菜谱做。", "I'll clear the pot, then start the dish you requested."},
    },
    recipe_ready = {
        {"出锅啦，闻着就不错。", "Dinner's ready. That smells good."},
        {"这份先收好，饿了就有饭吃。", "I'll keep this meal for when I'm hungry."},
        {"没白忙活，热乎饭到手了。", "Worth the effort. A fresh meal is ready."},
        {"做好啦，带上继续赶路。", "All done. I'll take it along."},
    },
    cook = {
        {"热乎一点，吃着也舒服些。", "Something hot always sits better."},
        {"慢慢烤，别烤焦了。", "Easy does it, mustn't burn it."},
        {"等一小会儿就好了。", "Just a little longer."},
        {"先把这份食物处理好。", "Let me get this one ready first."},
        {"火候要看仔细些。", "I'd better watch the heat closely."},
        {"能好好吃上一顿就好了。", "A proper meal would be so nice."},
    },
    eat = {
        {"先吃一点，再继续吧。", "A bite first, then back to it."},
        {"肚子舒服些，才有力气。", "It's easier to keep going on a full stomach."},
        {"这顿饭来得正好。", "This meal came just in time."},
        {"不能只顾着忙呀。", "I mustn't get so busy that I forget to eat."},
        {"慢慢吃，不着急。", "No need to rush a meal."},
        {"吃过了，就能继续赶路了。", "That's better. Now I can carry on."},
    },
    fed = {
        {"谢谢你，还记得给我留一份。", "Thank you for saving a share for me."},
        {"收到啦，你也别饿着自己。", "Got it! Don't let yourself go hungry either."},
        {"你这么照顾我，我很开心。", "It makes me happy, you looking after me like this."},
        {"谢谢，这一口很暖心。", "Thank you. That bite really warmed me up."},
        {"有你惦记着，真好。", "It's lovely, being thought of."},
        {"我吃到了，你也要照顾好自己呀。", "I've eaten. Now you take care of yourself too."},
        {"谢谢你陪我吃东西。", "Thank you for sharing a bite with me."},
        {"这份心意我收下了。", "I'll treasure the thought."},
    },
    fed_careful = {
        {"谢谢你，不过这个要小心吃呢。", "Thank you, though this one needs eating carefully."},
        {"我吃下了，接下来缓一缓。", "Down it went. I'll take it easy for a bit."},
        {"这口滋味有些特别。", "That had a rather... unusual taste."},
        {"别担心，我会留意自己的身体。", "Don't worry, I'll keep an eye on how I feel."},
        {"下次我们找些更合适的吃吧。", "Let's find something better suited next time."},
        {"你的心意我知道啦，食物也要挑一挑。", "I know you meant well, but let's be a bit choosier."},
    },
    gift = {
        {"给我的吗？谢谢，我会好好用的。", "For me? Thank you, I'll put it to good use."},
        {"有这个在，路上就安心些了。", "With this along, the road feels safer."},
        {"谢谢你替我准备这些。", "Thank you for getting this ready for me."},
        {"我收好了，你别担心。", "It's safely stowed. Don't worry."},
        {"又麻烦你照顾我了。", "You're looking after me again. Thank you."},
        {"这份装备，我会珍惜的。", "I'll take good care of this."},
        {"谢谢，有需要的时候就能用上了。", "Thank you. It'll be ready when I need it."},
        {"你也给自己留好装备呀。", "Do keep some gear for yourself as well."},
    },
    feed_player = {
        {"你先吃一点，别饿着自己。", "Eat something first. Don't go hungry."},
        {"慢慢吃，我会陪着你的。", "Take your time. I'll stay right here with you."},
        {"看起来饿了，先补充一点力气吧。", "You look hungry. Get your strength back first."},
        {"这份食物给你，路还要继续走呢。", "This is for you. We've still got a long way to go."},
        {"先吃饱一点，再继续忙，好吗？", "Eat your fill first, then back to work, all right?"},
        {"别只顾着赶路，也要照顾好自己。", "Don't just push on. Look after yourself too."},
        {"我这里还有一些，先拿去吃吧。", "I've got some to spare. Here, take it."},
        {"希望这一口能让你舒服些。", "I hope this makes you feel a bit better."},
    },
    beefalo_feed = {
        {"来，吃点东西，慢慢变乖。", "Here, have a bite. Take it slow."},
        {"别闹，吃饱了才有力气驮我们。", "Easy now. You need a full belly to carry us."},
        {"树枝和草都有，今天一定把你哄好。", "Twigs and grass for you. I will win you over today."},
        {"顺从一点嘛，我还给你留了好吃的。", "Be a little more obedient. I saved you something tasty."},
        {"来，先把肚子填到舒服。", "Come on, fill your belly until you are comfortable."},
        {"这头牛的脾气，还得慢慢练。", "This beefalo has quite the temper. We will train patiently."},
        {"别顶我，我是来送饭的。", "No headbutting! I brought dinner."},
        {"一口一口来，咱们慢慢熟悉。", "One bite at a time. We will get to know each other."},
        {"吃饱就歇会儿，不急着赶路。", "Have a rest after eating. The road can wait."},
        {"好好吃饭，下次可别把我甩下来了。", "Eat up, and please do not throw me off next time."},
    },
    beefalo_cook = {
        {"我去煮些蒸树枝，给牛准备口粮。", "I am cooking beefalo feed for our ride."},
        {"树枝够多了，正好做点牛喜欢的。", "There are enough twigs. Time to make the beefalo's favorite."},
        {"先把牛照顾好，赶路才省心。", "A well cared for beefalo makes the road easier."},
    },
    player_takes_food = {
        {"饿了就直说嘛，怎么还拿我的口粮。", "Hungry? You could have asked before taking my rations."},
        {"最近穷得吃不起饭了吗？我这里还有一点。", "Having trouble finding dinner? I have some to share."},
        {"拿吧拿吧，别把自己饿坏了。", "Go on, take it. Do not let yourself go hungry."},
        {"原来你也惦记着我的这口饭呀。", "So you had your eye on my dinner too."},
        {"慢慢吃，别噎着。我可不跟你抢。", "Eat slowly. I will not fight you for it."},
        {"下次饿了叫我一声，咱们一起吃。", "Tell me next time you are hungry. We can eat together."},
    },
    player_takes_sack = {
        {"连我的饭盒也拿走？你是饿得有多急呀。", "Taking my lunchbox too? You must be really hungry."},
        {"这个饭盒我还要用呢，别拿去卖了。", "I still need that lunchbox. Do not go selling it."},
        {"拿我的熊桶做什么，自己没有饭盒吗？", "What are you doing with my sack? Do you not have one?"},
        {"饭盒可以借你，记得里面的吃的也别浪费。", "You can borrow the lunchbox, but do not waste the food inside."},
        {"我的午饭跟着你跑了，晚上可得请我吃饭。", "My lunch is going with you. Dinner is on you tonight."},
        {"你拿饭盒，我拿什么装饭呀？", "With you taking the lunchbox, where will I put my meals?"},
    },
    beefalo_cooked = {
        {"蒸树枝好了，给我们的牛留着。", "The beefalo feed is ready. I will save it for our beefalo."},
        {"这一锅可不是给咱们吃的哦。", "This pot is not our dinner!"},
        {"牛的口粮收好了，下次饿了就有得吃。", "Beefalo rations packed for next time."},
    },
    hurt = {
        {"有点疼……我会小心的。", "That stung... I'll be more careful."},
        {"先避开这里。", "I should get away from here."},
        {"我还撑得住。", "I can still hold on."},
        {"别再这样了，好吗？", "Please, not again."},
        {"缓一口气，我还能走。", "Just need a breath. I can still move."},
        {"得更小心一点了。", "I'll have to be more careful now."},
    },
    meal_open = {
        {"我看看随身带的食物。", "Let me check the food I brought."},
        {"先打开熊桶，吃一点再走。", "I'll open my sack and have a bite."},
        {"吃的就在身边，不用跑远。", "My food is right here."},
        {"我带了口粮，先补充点力气。", "I packed a meal. Time to get some strength back."},
    },
    meal_take = {
        {"我从这里拿一点吃的。", "I'll take something to eat from here."},
        {"先吃需要的，剩下的放回来。", "I'll eat what I need and return the rest."},
        {"这里还有食物，正好补充一下。", "There's food here. Just what I need."},
        {"拿出来吃一口，不会都带走的。", "I'll have a bite and leave the rest here."},
    },
    meal_return = {
        {"剩下的放回原处。", "The rest goes back where it belongs."},
        {"吃好了，把余下的收好。", "That was enough. I'll put the rest away."},
        {"刚才暂存的食物，现在可以放回去了。", "I can return the food I kept for later now."},
        {"没吃完的留在这里保管。", "I'll leave the uneaten food here."},
    },
    player_attack = {
        {"你为什么要攻击我？先停手，我们可以谈谈。", "Why are you attacking me? Stop. We can talk."},
        {"别再打我了，我不会对你动手。", "Please stop hitting me. I do not want to fight you."},
        {"我是来帮忙的，不是来挨打的。", "I came to help, not to be beaten."},
        {"你再这样，我只能保护自己了。", "If you keep this up, I will have to defend myself."},
    },
    ghost_return_question = {
        {"我会先留在这里。可以让我回去拿东西吗？", "I will stay here for now. May I go back for the things we need?"},
        {"如果你同意，我可以回去把东西带回来。", "If you agree, I can go back and bring the things here."},
        {"我能回去取一些物资，再回来找你吗？", "May I fetch some supplies and come back to you?"},
    },
    fight = {
        {"小心，我会照应你的。", "Careful! I've got your back."},
        {"别慌，我们看准时机。", "Don't panic. We'll wait for the right moment."},
        {"我不会让你独自应付的。", "I won't let you face this alone."},
        {"保持距离，别受伤。", "Keep your distance. Don't get hurt."},
        {"来不及躲，就一起应对吧。", "No time to run, we'll take it on together."},
        {"我在这里，不要怕。", "I'm right here. Don't be afraid."},
        {"看准时机，别让它喘过气来。", "Watch the opening. Don't let it breathe."},
        {"我来牵制它，你找机会攻击。", "I'll keep it busy. Find an opening."},
        {"别乱了阵脚，我们一起上。", "Stay steady. We take it together."},
        {"退一步，等它先出手。", "One step back. Let it swing first."},
        {"我还能打，继续！", "I can still fight. Keep going!"},
    },
    fight_boss = {
        {"这么大的家伙也不是不能打，跟紧我！", "Even something that big can be beaten. Stay with me!"},
        {"巨兽来了，别站在它正面！", "A giant is here. Don't stand in front of it!"},
        {"我来帮你牵制它，抓住机会！", "I'll help hold it off. Take the opening!"},
        {"盯住它的动作，别被范围攻击卷进去。", "Watch its movement. Don't get caught in the area attack."},
        {"这场仗有点大，但我们不是一个人。", "This is a big fight, but we're not alone."},
        {"看准时机，别让它喘过气来。", "Watch the opening. Don't let it breathe."},
        {"我们先拆掉它的节奏，再找机会重击。", "Break its rhythm first, then strike hard."},
        {"它要放大招了，散开！", "It's preparing something big. Spread out!"},
        {"别站在它脚下，范围攻击要来了。", "Don't stand under it. An area attack is coming."},
    },
    flee = {
        {"这里不安全，先走吧。", "It's not safe here. Let's go."},
        {"活着离开，比什么都重要。", "Getting out alive matters more than anything."},
        {"我们换条路。", "Let's take another route."},
        {"别硬撑，退开一点。", "Don't push it. Back off a little."},
        {"先离远些，再想办法。", "Let's get clear first, then think."},
        {"跟紧些，我们离开这里。", "Stay close. We're leaving."},
    },

    -- ---------- 打招呼与关心（会自动加上"名字，"前缀）----------
    greeting = {
        {"你好。", "hello."},
        {"见到你真好。", "it's good to see you."},
        {"一路还顺利吗？", "how has your day been?"},
        {"路上小心呀。", "take care out there."},
        {"忙累了就歇一会儿吧。", "rest a bit when you get tired."},
        {"希望你今天也平平安安。", "I hope today treats you kindly."},
    },
    care_health = {
        {"你还好吗？", "are you all right?"},
        {"你看起来受伤了，先缓一缓吧。", "you look hurt. Take a moment."},
        {"别太勉强自己，我陪你休息一会儿。", "don't push yourself. I'll rest here with you."},
        {"先照顾好自己，好吗？我有些担心你。", "look after yourself first, all right? I'm worried about you."},
    },
    care_hunger = {
        {"你要吃饱饱啊！", "make sure you eat plenty!"},
        {"肚子是不是饿了？我们找点吃的吧。", "getting hungry? Let's go find you something."},
        {"忙了这么久，要不要吃点东西呀。", "you've been at it a while. Fancy a bite?"},
        {"别饿着自己呀，我陪你找吃的。", "don't go hungry. I'll help you find some food."},
    },
    care_sanity = {
        {"你要好好休息啊！", "you really need some proper rest!"},
        {"是不是有些累了？我们慢一点吧。", "feeling worn out? Let's slow down."},
        {"别绷得太紧，停下来歇一会儿吧。", "don't wind yourself so tight. Stop and rest a while."},
        {"我在这里陪着你，安心休息一下吧。", "I'm right here with you. Rest easy."},
    },

    -- ---------- 收到放在身上的食物 ----------
    gift_sack = {
        {"谢谢你送的熊桶，做好的饭可以好好保存了。", "Thank you for the sack. My meals will keep well now."},
        {"这下随身的料理有地方放了，谢谢你。", "Now I have somewhere to keep my meals. Thank you."},
        {"我会把料理收进去，好好用它。", "I'll put my meals inside and take good care of it."},
    },
    gift_food = {
        {"这些吃的先放我这里吗？我会好好收着。", "Am I holding this food for you? I'll keep it safe."},
        {"谢谢，我先替你拿着。", "Thank you. I'll carry it for you."},
        {"有吃的在身上，心里踏实多了。", "Food in my bag puts my mind at ease."},
        {"这份口粮我收下啦。", "I'll take these rations, then."},
        {"你总是想着让我吃饱。", "You're always making sure I'm fed."},
    },
    gift_food_settled = {
        {"这些吃的一直放在我这儿，谢谢你惦记着。", "This food has been with me all this time. Thank you for thinking of me."},
        {"你给的这份口粮，我一直留着呢。", "I've been keeping the rations you gave me."},
        {"有人愿意分东西给我，真的很开心。", "It really does make me happy, being shared with."},
        {"这份心意我记下了。", "I won't forget this kindness."},
        {"谢谢你，我不会饿肚子了。", "Thank you. I won't go hungry now."},
    },

    -- ---------- 原地待命 ----------
    hold_position = {
        {"好，我就在这里等你。", "Okay, I'll wait for you right here."},
        {"我不走远，就在这附近。", "I won't go far. Just around here."},
        {"知道了，我留在这儿。", "Got it. I'll stay put."},
        {"我在这里守着，你放心去吧。", "I'll keep watch here. Go on, don't worry."},
        {"好的，我原地待命。", "Right. Holding this spot."},
    },
    hold_idle = {
        {"我还在这里等着呢。", "Still here, still waiting."},
        {"就在这附近走走，不会走远的。", "Just pacing about. I won't wander off."},
        {"你回来的时候，我一定还在。", "I'll be here when you get back."},
        {"这地方我记住了。", "I've got this spot memorised."},
        {"慢慢来，我不急。", "Take your time. I'm in no hurry."},
    },

    -- ---------- 切换基地 ----------
    base_set = {
        {"好，以后这里就是我们的家了。", "Good. From now on, this is home."},
        {"我记住这个地方了。", "I've marked this place in my mind."},
        {"新家就定在这里吧。", "Let's make this the new home."},
        {"以后我就在这附近等你。", "I'll be waiting around here from now on."},
        {"这里挺好的，我喜欢。", "It's nice here. I like it."},
    },
    base_idle = {
        {"在家附近走走，心里安稳。", "Strolling near home. It's calming."},
        {"这里就是家了呢。", "So this is home now."},
        {"我不会离家太远的。", "I won't stray far from home."},
        {"家里有吃的就好办了。", "As long as there's food at home, we'll be fine."},
        {"回到熟悉的地方，真舒服。", "It's lovely to be somewhere familiar."},
    },

    -- ---------- 迟来的伙伴（世界已经过了 200 天）----------
    late_join = {
        {"这个世界已经走了很久了呢，我就不乱盖房子了。", "This world has come a long way already. I won't go putting up buildings."},
        {"你们已经安顿好了，我跟着你们就行。", "You're all settled in. I'll just tag along."},
        {"我只采一点草和树枝，别的东西先不动。", "I'll only pick grass and twigs. I'll leave the rest be."},
        {"这里的东西都是你们的，我不会乱拿。", "Everything here is yours. I won't help myself."},
    },
    wander = {
        {"没什么吃的了，我到处走走看看。", "Nothing left to eat. I'll go have a look around."},
        {"出去转一圈，说不定能找到点什么。", "I'll take a wander. Might turn something up."},
        {"路还长，慢慢走吧。", "It's a long road. I'll take it slow."},
        {"我去远一点的地方看看。", "I'll try a little further out."},
    },
    ask_pickup = {
        {"地上这些东西，我可以捡起来吗？", "May I pick up the things on the ground here?"},
        {"这些不是草和食物，要我收起来吗？", "These aren't grass or food. Shall I gather them up?"},
        {"我看到一些材料，需要我捡吗？说一声可以就行。", "I see some materials. Want me to grab them? Just say yes."},
        {"这些东西能动吗？我怕是你们要用的。", "May I touch these? I'd hate to take something you need."},
    },
    pickup_allowed = {
        {"好，那我就帮你们把东西收起来。", "Right, I'll gather things up for you then."},
        {"明白了，以后看到材料我就捡。", "Understood. I'll pick up materials from now on."},
        {"谢谢，我会小心收好的。", "Thank you. I'll keep them safe."},
    },

    -- ---------- 死亡与复活 ----------
    revived_thanks = {
        {"谢谢你把我带回来……我还以为再也见不到你了。", "Thank you for bringing me back... I thought I'd never see you again."},
        {"是你救了我吗？谢谢，我记住了。", "Was it you who saved me? Thank you. I won't forget it."},
        {"我回来了。谢谢你没有放弃我。", "I'm back. Thank you for not giving up on me."},
        {"这份恩情，我会用行动还的。", "I'll repay this. You'll see."},
        {"还能站在这里，多亏了你。", "I'm still standing, and that's thanks to you."},
    },
    revive_player = {
        {"别怕，我在这儿，回来吧。", "Don't be afraid. I'm here. Come back."},
        {"把这个拿好，我们还没走完呢。", "Hold onto this. We're not finished yet."},
        {"我来晚了，抱歉。快回来。", "I'm sorry I was slow. Hurry back."},
        {"这颗心给你，站起来吧。", "This heart is for you. Get up."},
        {"我不会丢下你的。", "I'm not leaving you behind."},
    },
    revive_drop = {
        {"我把它放在这儿了，去碰一下就能回来。", "I've set it down here. Touch it and you'll come back."},
        {"这个能带你回来，就在你脚边。", "This will bring you back. It's right by your feet."},
        {"能帮的我都放下了，剩下的靠你自己。", "I've left what I can. The rest is up to you."},
        {"看到了吗？去作祟它。", "See it? Go on, haunt it."},
    },

    -- ---------- 更换伙伴（告别与到来）----------
    -- 告别是说给在场所有人听的，所以不要在这里写任何具体名字。
    farewell = {
        {"大家……我要走了。谢谢你们陪我这一程。", "Everyone... I'm leaving. Thank you for walking this far with me."},
        {"该说再见了。别送我，我自己走就好。", "It's time to say goodbye. Don't see me off, I'll manage."},
        {"我会记得这里的每一天的。保重。", "I'll remember every single day here. Take care."},
        {"不用担心我，很快会有人来陪你们的。", "Don't worry about me. Someone will be along soon to keep you company."},
        {"路要分开走，但我不会忘记你们。", "Our paths split here, but I won't forget you."},
    },
    switch_arrive = {
        {"你们好，以后请多关照。", "Hello, everyone. I hope you'll have me."},
        {"听说这里有人在等我？", "I heard someone was waiting for me?"},
        {"希望我们能成为好朋友", "I hope we can be good friends."},
        {"这是哪，有人在吗？", "Where is this? Is anyone there?"},
    },

    -- ---------- 冷热与光线 ----------
    cold = {
        {"有点冷了，我加件保暖的。", "Getting cold. I'll put something warm on."},
        {"冻得手都僵了，先穿上吧。", "My hands are going stiff. Time to bundle up."},
        {"这天气可真凉。", "This weather really is bitter."},
    },
    hot = {
        {"太热了，我换个凉快点的。", "Far too hot. I'll change into something cooler."},
        {"这个天气，得想办法降降温。", "In this heat I need to cool down somehow."},
        {"晒得有点晕，先遮一遮。", "The sun is making me dizzy. Let me cover up."},
    },
    worn_out = {
        {"这件快坏了，我先脱下来收好。", "This one is about to give out. I'll take it off and keep it."},
        {"再穿下去就彻底坏了，先收起来吧。", "Any longer and it'll break for good. I'm putting it away."},
        {"东西快用坏了，得省着点。", "This is nearly worn through. Better save it."},
    },
    dark = {
        {"天黑了，我点个灯。", "It's gone dark. Let me light something."},
        {"暗下来了，跟紧我。", "It's getting dark. Stay close to me."},
        {"有光就安心多了。", "A bit of light makes all the difference."},
    },
}

M.replies = {
    describe_carry_statue = {"我去搬最近的雕像，然后跟着你走。", "I'll carry the nearest statue and follow you with it."},
    carry_statue_follow = {"雕像搬好了，我会抱着它跟着你。附近有牛的话，我再骑牛搬。", "The statue is in my arms. I'll follow you with it, and ride if I have a beefalo nearby."},
    carry_statue_mount = {"抱稳了，雕像也能坐牛赶路。", "Hold tight. Even a statue can go for a ride."},
    carry_statue_none = {"附近没有我能搬的雕像。", "There is no statue nearby that I can carry."},
    describe_rockfruit = {"我先用工具开采石果，没有工具就摘附近的石果灌木。", "I'll mine the rock fruit with a tool, or pick nearby bushes if I have no tool."},
    describe_bullkelp = {"好的，摘完我再放进冰箱。", "OK,I'll put it in a fridge when I'm done."},
    describe_dry_meat = {"我把身上能晾的食材都挂到附近的晾肉架上。", "I'll hang everything I can dry on the nearby drying racks."},
    dry_meat_done = {"能晾的食材都挂好了，接下来交给风和太阳。", "Everything that could be dried is hanging. The wind and sun can take it from here."},
    pet_unknown = {"你想领养哪种宠物？比如小蛾子、小座狼或者一吃。", "Which pet would you like? A Mothling, Vargling, or Eets?"},
    pet_full = {"我已经有小伙伴要照顾，不能再领养啦。", "I already have a companion to care for."},
    pet_materials = {"身上的领养材料还没凑齐，准备好了再叫我吧。", "I'm missing some adoption supplies. Ask again once I'm carrying them."},
    pet_no_den = {"没找到能到达的宠物巢穴，这次先回来。", "I couldn't find a reachable Rock Den. I'll come back for now."},
    pet_unavailable = {"这次没能办成领养，我先回来找你。", "I couldn't complete the adoption. I'm coming back."},
    pet_prepare = {"材料够了，我去宠物巢穴领养，接到它就回来找你。", "I have the supplies. I'll visit the Rock Den and bring our new friend back."},
    pet_done = {"领到了！我带着新朋友回来找你。", "All adopted! I'm coming back with our new friend."},
    describe_explore = {"我去没走过的地方探探路，需要我就叫我回来。", "I'll explore somewhere new. Call me back when you need me."},
    describe_fish = {"我去找池塘钓鱼，钓竿坏了有材料就再做一根。要停就叫我。", "I'll go fishing and make another rod if I have the materials. Call me when I should stop."},
    fish_no_rod = {"没找到能用的淡水钓竿，材料或附近的科技站也不够。", "I can't find a freshwater rod or the supplies and science station to make one."},
    fish_rod_done = {"钓竿用完了，现在没法再做一根，我先回来。", "My rod wore out and I can't make another right now. I'm coming back."},
    fish_rod_missing = {"钓竿不在身边了，我先回来。", "My fishing rod is missing. I'll come back for now."},
    ghost_revive_nearby = {"我去作祟附近的复活物品，等我回来。", "I'll haunt a nearby resurrection item. Wait for me."},
    ghost_revive_portal = {"我去大门那里复活，回来再找你。", "I'll revive at the portal, then come back to you."},
    ghost_revive_none = {"附近没有能让我作祟复活的东西。", "There's nothing I can haunt to revive within sixteen units."},
    ghost_revive_no_portal = {"这个世界里没找到绚丽之门或天体传送门。", "I couldn't find a Florid Postern or Celestial Portal in this world."},
    ghost_revive_failed = {"这次没能复活，附近可用的办法都试过了。", "I couldn't revive. I've tried the available options nearby."},
    ghost_revive_return = {"我活过来了，这就回来找你。", "I'm alive again. I'm coming back to you."},
    ghost_revive_return_blocked = {"我已经复活了，但回去的路被挡住了。来接我一下吧。", "I'm alive, but the way back is blocked. Please come meet me."},
    bookstation_prepare = {"好，我找齐材料，把书架放在你脚下这块地皮的中央。", "I'll gather the materials and place a bookshelf in the centre of your turf tile."},
    bookstation_make_room = {"你挡住书架的位置啦，我先带你往旁边挪一点。", "You're standing where the bookshelf goes. Let's move you aside a little."},
    bookstation_blocked = {"这里放不下书架，或者旁边没有安全的落脚处。换块空地再叫我吧。", "The bookshelf is blocked, or there isn't a safe place to step aside. Please choose a clear tile."},
    bookstation_cannot_make = {"做书架需要两个活木、四张莎草纸和一支羽毛笔，身上和附近箱子的材料还没凑齐。", "A bookshelf needs two living logs, four papyrus and a feather pencil. My inventory and nearby chests don't have enough."},
    bookstation_done = {"书架放好了，就在这块地皮的中央。书也有地方休息了。", "The bookshelf is ready, right in the centre of the tile. A resting place for our books."},
    book_last_stored = {"这本书只能再读一次，先放在书架里养护。确实急用的话，三十秒内再叫我读这本书吧。", "This book has one reading left. I'll keep it on the shelf to recover. Ask again within thirty seconds if it's urgent."},
    book_last_keep = {"这本书只能再读一次，附近没有能存放它的书架，我先留着。三十秒内再叫我，我就读。", "This book has one reading left and no available shelf nearby. I'll keep it. Ask again within thirty seconds and I'll read it."},
    book_used_up = {"读完了，这本书也用尽了。下次得准备一本新的。", "Finished. That was the book's final reading. We'll need another copy."},
    book_read_failed = {"这次没能读成，可能是书被移走了，或现在不适合施展它的效果。", "I couldn't finish reading. The book may have moved, or its effect cannot be used right now."},
    -- ---------- 聊天指令的固定回复 ----------
    follow_ok = {"好，我跟你走。", "Okay, I'll come with you."},
    follow_busy = {"我现在先陪另一位朋友。", "I'm keeping another friend company just now."},
    follow_unfamiliar = {"我们还不够熟悉。", "We don't know each other well enough yet."},
    ride_ok = {"好，我骑牛追上你。", "Okay, I'll ride after you."},
    ride_stop_ok = {"好，我下来走。", "Alright, I'll walk from here."},
    ride_unavailable = {"现在没有能骑的牛，我先走过去。",
        "I don't have a rideable beefalo right now. I'll walk."},
    ride_not_following = {"你先让我跟着你，我才能骑牛去找你。",
        "Ask me to follow you first, then I can ride after you."},
    affinity_work = {"好感度超过50后，我才愿意帮你做这些事。",
        "Once we're past 50 affinity, I'd be glad to do that for you."},
    affinity_items = {"好感度达到20后才能动我的物品哦。",
        "You'll need 20 affinity before you can touch my things."},
    affinity_name = {"好感度达到100后，再为我取个名字吧。",
        "Reach 100 affinity and you can give me a name."},
    affinity_locked = {"好感度达到{1}后才能使用这个功能。",
        "That needs {1} affinity before I can do it."},
    affinity_skin = {"好感度达到50后才能换装。",
        "I'll change outfits once we reach 50 affinity."},
    name_invalid = {"请取一个简短的名字，不要带换行或特殊标记。",
        "Please pick a short name, with no line breaks or odd symbols."},
    name_ok = {"好呀，以后就叫我{1}。", "I like it! Call me {1} from now on."},
    special_no_book = {"我找不到这本书。", "I can't find that book."},
    special_no_food = {"没有找到这份料理，或者它不在身上。", "I couldn't find that meal in my inventory."},
    special_cannot_make = {"材料或设备不够，我现在做不了。", "I don't have the materials or station to make that."},
    recipe_batch_done = {"已经做好{1}份啦，剩下的材料或厨具条件不够再做一锅了。", "I've made {1} portions. I can't start another pot with the remaining ingredients and available cookware."},
    recipe_inventory_full = {"身上装不下了，我先停一停，锅里的料理给你留着。", "I'm out of room. I'll stop here and leave anything in the pot for you."},
    special_device_place_failed = {"厨具做好了，但附近没有合适的空地，我先不乱放。", "The cookware is ready, but I couldn't find a clear place nearby."},
    special_recall = {"好，我让阿比盖尔回去休息一会儿。", "All right, I'll have Abigail rest for a while."},
    special_read_ok = {"我去找这本书来读。", "I'll find that book and read it."},
    special_spice_ok = {"好，我来给这份料理调味。", "I'll season that meal."},
    special_command_ok = {"好，我来准备。", "All right, I'll prepare it."},
    no_backpack = {"附近没有能用的背包，我先不制作新的。",
        "There's no backpack I can use nearby, and I won't make a new one."},
    backpack_unreachable = {"那个背包我现在过不去，等这边安全一点再说。",
        "I can't get to that backpack right now. Let's wait until it's safer."},
    no_tool = {"附近没有可用的工具，我暂时做不了这个。",
        "I can't find a tool I can use, so I'll leave this for now."},
    hoe_incomplete = {"能整理的坑都整理好了，有些位置被作物或障碍挡住，我处理不了，你能帮帮我吗。",
        "I've tidied every hole I could. Some are blocked by crops or obstacles and I can't manage those. Could you help?"},

    -- ---------- 指令说明 ----------
    describe_butterfly = {"好，我去打你周围的蝴蝶，不会追太远。", "I'll hunt the butterflies around you without straying too far."},
    butterfly_none = {"你附近没有我现在能打到的蝴蝶。", "There are no butterflies I can reach around you right now."},
    butterfly_done = {"附近能打的蝴蝶已经处理好了，飞远的就不追了。", "I've finished with the nearby butterflies. I won't chase the ones that flew away."},
    describe_sit = {"好，我找最近的空椅子坐下。", "I'll take the nearest free seat."},
    sit_unavailable = {"附近没有能坐的空椅子，我先站着吧。", "There isn't an available seat nearby. I'll stand for now."},
    sit_stop_ok = {"好，我下来了，先活动一会儿。", "All right, I'm getting up. I'll stretch my legs for a while."},
    describe_dig_grass = {"我去拿铲子，把你附近能挖的草丛挖出来。", "I'll get a shovel and dig up the grass tufts around you."},
    describe_dig_sapling = {"我来挖附近的树苗，挖出来的也会收好。", "I'll dig up the nearby saplings and collect them."},
    describe_dig_stump = {"我来清理附近的树根，长着的树就不动了。", "I'll clear the nearby stumps and leave the living trees alone."},
    dig_full = {"身上装不下了，我先停手，免得挖出来没地方放。", "My bags are full. I'll stop digging until there's room."},
    dig_none = {"你附近没有我现在能挖的目标。", "There are no matching targets I can dig up around you right now."},
    dig_done = {"这一圈能挖的都处理好了。", "I've finished the reachable targets in this area."},
    describe_hoe = {"锄禾日当午，汗滴禾下土。",
        "Hoeing at noon, sweat dripping into the soil."},
    describe_water = {"植物宝宝要多喝水呀！",
        "The little plants need plenty to drink!"},
    describe_chop = {"砍树，砍树，如果能盖房子就好了。",
        "Chop, chop... I do wish we could build a house out of it."},
    describe_mine = {"今天扮演的角色是矿工，嘿呦！",
        "Today I'm playing the miner. Heave-ho!"},
    describe_grass = {"我帮你收些好东西。",
        "I'll gather some good things for you."},
    describe_harvest = {"我来帮你收菜吧。",
        "Let me bring the harvest in for you."},
    describe_seeds = {"我会帮你捡种子，为我们的丰收计划做准备。",
        "I'll collect seeds for you, all part of our big harvest plan."},
    describe_tidy = {"我会帮你收拾这里的。",
        "I'll tidy this place up for you."},
    describe_hold = {"我会待在这里等你~",
        "I'll wait here for you, and help myself to a nearby icebox if I get hungry."},
    describe_base = {"以后这里就是我的家啦！",
        "From now on, this is my home!"},
    base_needs_follow = {"你得先让我跟着你，我才知道要搬到哪里。",
        "Ask me to follow you first, then I'll know where to move to."},
    switch_needs_follow = {"抱歉，我还不想走。",
        "Sorry, I don't want to leave yet."},
    -- 玩家说"带走吧/送你/不要了"：走的时候把身上的东西一起带走
    farewell_gift_ok = {"那我就都收下了，走的时候一起带走。",
        "Then I'll keep it all, and take it with me when I go."},
    farewell_gift_cancel = {"好，那我走的时候把东西留下。",
        "Alright, I'll leave everything behind when I go."},
}

return M
